name: CatSense
version: '${version}'
main: top.mrxiaom.catsense.CatSense
api-version: 1.13
depend:
  - Vault
  - PlaceholderAPI
commands:
  catsense:
    description: awa
  locks:
    description: awa
